// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnn0Ro1MMKNLLSgRReXc1TYyWUl8wUgCk',
    appId: '1:284271437843:android:35d71c268fce60a79b37e6',
    messagingSenderId: '284271437843',
    projectId: 'cusipco-7a29c',
    storageBucket: 'cusipco-7a29c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfx5f4fG-OnmCKlbOE26qGlovCfuWJZi8',
    appId: '1:284271437843:ios:672bbcd93891dbf19b37e6',
    messagingSenderId: '284271437843',
    projectId: 'cusipco-7a29c',
    storageBucket: 'cusipco-7a29c.appspot.com',
    androidClientId:
        '284271437843-8gq5obvjc900gocsrk00mums4t5ji5dj.apps.googleusercontent.com',
    iosClientId:
        '284271437843-suo5n0ctg9g5k9om4g4dcv7u057cud51.apps.googleusercontent.com',
    iosBundleId: 'com.cusipco.services',
  );
}
